kafka.bootstrap.servers=localhost:9092
kafka.topic.prosumenci=prosumenci-odczyty
kafka.topic.aggregated=prosumenci-agregaty-l1
generator.interval.ms=5000
generator.prosumenci.count=20
generator.anomaly.probability=0.05
generator.disorder.max.ms=30000