kafka.bootstrap.servers=localhost:9092
kafka.topic.ecommerce=ecommerce-transakcje
generator.interval.ms=2000
generator.users.count=500
generator.anomaly.probability=0.03
generator.disorder.max.ms=30000